server:
  port: 9002

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: localhost:1111 # 集群nacos
#        server-addr: 123.57.25.100:8848 // 单机nacos



management:
  endpoints:
    web:
      exposure:
        include: '*'